# Generated by Django 5.1.7 on 2025-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
